### ISSUE TITLE
g_riflearena and ft/ca -> limited ammo

### ISSUE THREAD

**Issue by DefaultUser** [MarioSMB/modpack#32]
Ammo is limited if g_riflearena is active and the gametype is set to ft or ca.
Both gametypes set limited ammo in "SetStartItems"
`MUTATOR_HOOKFUNCTION(ca, SetStartItems)
{
	start_items       &= ~IT_UNLIMITED_AMMO;
        ...
`
Since there are no pickups, there should be unlimited ammo in riflearena

**Comment by MarioSMB** [comment]
Should be fixed now, thanks for reporting.
