### ISSUE TITLE
Empty (0 byte) quickmenu.pk3 file in dlcache

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [MarioSMB/modpack#35]
The file "quickmenu.pk3" does not exist server side is this file being created by the mod?
I upgraded zzz-quickmenu_22.pk3 to zzz-quickmenu_23.pk3 (then renamed and added modded it; add hats/creeper)
I realize the quickmenu is a required dependency, but is the name/version locked? if so that would be a bug IMO

**Comment by MarioSMB** [comment]
The pk3 can have any name, just make sure you also rename the .serverpackage file inside the pk3, and host the new pk3 on your web host for serving maps, otherwise clients won't be able to download it.

**Comment by GM-Script-Writer-62850** [comment]
Then why does the game keep requesting a file named "quickmenu_22.pk3" (not even with a zzz prefix) which results in a 404 error as there is not one on the server nor the dl server

**Comment by MarioSMB** [comment]
Not sure why it wouldn't have the zzz- prefix (maybe some accident in the past), but you need to run the fs_rescan command in your server's console and change the map to apply package changes if you're not restarting the server each time you test.  
If such a file somehow exists, you can find it with this command in the server's console: which quickmenu_22.pk3

**Comment by GM-Script-Writer-62850** [comment]
Console says it does not exist anywhere, i have been restarting the server as i did not know about `fs_resan`
every time the client makes a request for `quickmenu_022.pk3` (sorry i forgot the 0 earlier) and it does not exist on my server, dl.xonotic.co, nor xonotic.devfull.de/packages
* i setup a PHP script to handle files from multiple servers using mine as a last resort

why the client is asking for a pk3 that is not even present on the server i do not know i am assuming it has to be the mod causing it to ask for it

**Comment by MarioSMB** [comment]
The mod itself doesn't ask for packages, this is most certainly a configuration/file error.  

Most likely, you have quickmenu_022.pk3 in sv_curl_serverpackages. This cvar doesn't need to include anything by default, content packages add themselves to it automatically.

**Comment by GM-Script-Writer-62850** [comment]
nope, i just thought of something, before i compiled xonotic i put all the mod dependencies in the games main data folder guess i should remove them from there
just removed it and it stopped asking for it
sorry for bugging you with this
