### ISSUE TITLE
Incorrect position and rotation of hats

### ISSUE THREAD

**Issue by somethingswrong** [MarioSMB/modpack#39]
Hats appear at the center of character (hips) instead of where the head is. Their rotation is incorrect too. I tried to change their position, but that doesn't help much, because hats still don't follow the animation (looking up/down, crouching).

I'm using SMB modpack from master and Xonotic server is also compiled from master.

**Comment by MarioSMB** [comment]
So far I've been unable to reproduce this... Is it possible this is caused by custom code in your own modifications?

**Comment by somethingswrong** [comment]
It happens on an unmodified server too. I made sure to use the current Xonotic master.
Can you try using this patch?
[Add-hats.zip](https://github.com/MarioSMB/modpack/files/2822481/Add-hats.zip)

**Comment by somethingswrong** [comment]
![xonotic hats](https://user-images.githubusercontent.com/45147276/52137037-71791080-2641-11e9-900d-de5ab8e0c79e.png)

**Comment by somethingswrong** [comment]
The problem was on my side.
