### ISSUE TITLE
Bonus nade time

### ISSUE THREAD

**Issue by mmm4m5m** [MarioSMB/modpack#48]
Looks like, the time for a new bonus nade depends of cl_maxfps and cl_netfps.

There is significant difference.
People with 600 fps get new bonus nade every 10 seconds.
People with 60 fps get new bonus nade every 90 seconds.

(Checked in Jeff vehicle server).

**Comment by MarioSMB** [comment]
Unfortunately, I am unable to manage issues occurring on Jeff's server, you may have more luck reporting it on his tracker: https://gitlab.com/spawncampers/jeff-modpack/-/issues

**Comment by mmm4m5m** [comment]
Thank you. Reported to jeff-modpack (in English) :)
All the best.

**Comment by mmm4m5m** [comment]
Addition - both apply to this modpack as well. I checked in another server - bonus nade time and buff timer #49 

Correction - cl_movement have greater effect for bonus nade time. Then cl_netfps. Then cl_maxfps.

And question - I would like to suggest ideas for fighting "trolls". 
Probably the best is in gitlab xonotic issues?
Anyway I will explain here as well, if you do not mind, please.

1) Make a list of client ID -> player nick. Allow nick changes only after 10 played/spectated games.
This will make it harder to disconnect, rename and rejoin to the other team, winning team.

2) In scoreboard and in chat show player number next to player nick. In rexuiz they have it like this "PlayerName # 3" (without spaces, where "# 3" is in dark color).
This will make it cristal clear if player renamed and chat or start a vote on behalf of another player.
(Note, in Jeff server, mute vote does not show player name at all. It shows only the number)

3) Add player icon, similar to "country flag" but without revealing the country. Uniq icon similar to default github profile picture based on client ID/IP address. If there is second connection from the same IP, then ignore client ID.
Again this will make it harder to disconnect, change name and play "smart ass".

I do not know if some of these are already available.
I do not know if these are part of server config, server scripts or xonotic core.

Thanks for your time and comments :)

I miss your SMB server with funny maps (and mushrooms to glow bug or get smaller size). Recently explained to someone and we wanted to check it, but we could not find the server in the list.
