### ISSUE TITLE
Buffs timer

### ISSUE THREAD

**Issue by mmm4m5m** [MarioSMB/modpack#49]
Looks like, the buffs timer depends of cl_movement.

When cl_movement is 0 (zero), then the timer for some buffs is not shown.
Timer for Medic buff is not shown and Medic never expire.
Buffs Flight, Ammo, Magnet does not work at all.

When you change cl_movement value to 1, then all buffs works normal.
If you already have Medic, then buff timer will show.
Magnet timer will show and work.

If you change cl_movement back to 0 BEFORE Medic expire, then you will have "endless" Medic (will not expire).

There are similar issues with other buffs, powerups, bonuses and super weapons.

(Checked in Jeff vehicle server).

**Comment by MarioSMB** [comment]
Thanks for reporting this problem, however as it has occurred on Jeff's server, you may want to instead report it to him: https://gitlab.com/spawncampers/jeff-modpack/-/issues

**Comment by mmm4m5m** [comment]
Reported to jeff-modpack. Thanks.
