### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by MarioSMB** [MarioSMB/modpack#50]
When running the build scripts to compile the modpack, the user will be prompted with a deletion message where they will need to press a button to continue, making it a bit more difficult to automate the build process. Perhaps cleaning the existing files should be an optional parameter?  

After successfully compiling the mod, an error will show: `mv: cannot stat './xonotic/qcsrc/csprogs-*.pk3': No such file or directory`

**Comment by LegendaryGuard** [comment]
Yeah, it was needed a option to clean existing files, when each time the user compiles. It is uncomfortable for the user to manually delete the files that were already compiled to get new ones. I thought a message to stop and decide would improve something for safety.
