### ISSUE TITLE
Survival: non-negative score

### ISSUE THREAD

**Issue by retsil2** [MarioSMB/modpack#53]
In Survival mode, negative scores make little sense. A player with negative score can join spectators then join game again to zero out the score. I propose making zero the lowest possible score.

**Comment by LegendaryGuard** [comment]
Gotta close the issue as Survival gametype has been moved to the [Xonotic codebase](https://gitlab.com/xonotic/xonotic-data.pk3dir). 
Feel free to open the issue [there](https://gitlab.com/xonotic/xonotic-data.pk3dir/-/issues).
