### ISSUE TITLE
Licensing problems,

### ISSUE THREAD

**Issue by Robert-CMDedu** [MarioSMB/modpack#56]
the copying.txt file in the mod/quake is for gplv2 when xonotic is under gplv3 and later
see https://github.com/xonotic/xonotic/blob/master/COPYING
darkplaces it self is under GPL V2 tho
pull request #57  should fix it

**Comment by Robert-CMDedu** [comment]
pull request #57 should fix it

**Comment by MarioSMB** [comment]
Thanks, I've merged your pull request to resolve this.  
The upper repository still contains a GPLv2 license, but seeing as Xonotic also has this it should be fine.
